version: "3.8"

services:

  customer-db:
    container_name: customer-db
    image: postgres:13.2-alpine
    environment:
      POSTGRES_DB: customer
      POSTGRES_USER: baggio
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    ports:
      - "5432:5432"

  fraud-db:
    container_name: fraud-db
    image: postgres:13.2-alpine
    environment:
      POSTGRES_DB: fraud
      POSTGRES_USER: baggio
      POSTGRES_PASSWORD: password
    ports:
      - "6432:5432"
