server:
  port: 8082
spring:
  application:
    name: notification
  datasource:
    url: jdbc:postgresql://postgres:5432/notification
    password: password
    username: baggio
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
  rabbitmq:
    addresses: rabbitmq:5672

rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    notification: notification.queue
  routing-keys:
    internal-communication: internal.notification.routing-key