apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 1
  template:
    metadata:
      name: notification
      labels:
        app: notification
    spec:
      containers:
        - name: customer
          image: baggio1103/notification:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
            - name: RABBIT_MQ_HOST
              value: rabbitmq
      restartPolicy: Always
  selector:
    matchLabels:
      app: notification
