version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:13.2-alpine
    environment:
      POSTGRES_DB: customer
      POSTGRES_USER: baggio
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped